sys_gen

Сообщение Yauhen » 11 май 2010, 22:00
Выполнение написанной мной процедуры доходит до
Executing get_n_interval_op14(sys_gen) of get_n_interval, line 98

И срс уходит в себя ;) прихватив с собой 50 процентов процессорного времени )

Это баг в sys_gen или у меня слишком слабый кампутер?

Yauhen


Сообщение LazurkinDA » 12 май 2010, 15:26
Скорее всего это баг. Покажите код вызова sys_gen и по какому шаблону происходит генерация.

LazurkinDA


Сообщение Yauhen » 12 май 2010, 16:04
ВсеЮ уже разобрался. :)

Код: выделить все
    В константах:
    pattern_find = [ _interval ->> {. 1_:: _f_t , 2_:: _s_t .};    ];
    ...
    В выполняемой части:
    sys_gen([
       1_: fixed_: pattern_find,
       3_: fixed_: {
                   {1_: _f_t,
                    2_: f_tone},
                    {1_: _s_t,
                    2_: s_tone},
                   {1_: _interval,
                    2_: interval_rel}
                }
    ],,)


Переменная interval_rel не была определена.
Но система почему-то не выдала ошибку, а повисла.

Недавно была похожая ситуация с searchSetStr5, но после парочки минут "висения" выскочило диалоговое окошко, в котором сообщилось об ошибке python.exe
Не переваривается вот такая конструкция. Аж в двух процедурах)

Код: выделить все
    genElStr3([
       1_: assign_: msg,
       2_: assign_: arc_: const_: pos_: arc1,
       3_: fixed_: chord
    ])

    searchSetStr5([
       1_: fixed_: chord,
       2_: assign_: arc_: pos_: const_: arc1,
       3_: assign_: node_: const_: node1,
       4_: assign_: arc_: pos_: const_: arc2,
       5_: assign_: node_: const_: attr1,
       set2_: set3_: set4_: set5_: fixed_: msg
    ])

Yauhen


Сообщение LazurkinDA » 12 май 2010, 17:58

    Yauhen писал(а):Переменная interval_rel не была определена.
    Но система почему-то не выдала ошибку, а повисла.


Значит в операторе нет проверки на это. Исправлю.

    Yauhen писал(а):Недавно была похожая ситуация с searchSetStr5, но после парочки минут "висения" выскочило диалоговое окошко, в котором сообщилось об ошибке python.exe
    Не переваривается вот такая конструкция. Аж в двух процедурах)


Странно. Я проверю. Вроде в коде все корректно.

LazurkinDA
